using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Wildcard.Utility;

namespace Wildcard
{
    internal class GameApplication
    {
        private Game CurrentGame;

        public void Start()
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.BackgroundColor = ConsoleColor.DarkGray;
            Print(@"

██╗    ██╗███████╗██╗      ██████╗ ██████╗ ███╗   ███╗███████╗   
██║    ██║██╔════╝██║     ██╔════╝██╔═══██╗████╗ ████║██╔════╝   
██║ █╗ ██║█████╗  ██║     ██║     ██║   ██║██╔████╔██║█████╗     
██║███╗██║██╔══╝  ██║     ██║     ██║   ██║██║╚██╔╝██║██╔══╝     
╚███╔███╔╝███████╗███████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║███████╗   
 ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝   
                                                                 
████████╗ ██████╗                                                
╚══██╔══╝██╔═══██╗                                               
   ██║   ██║   ██║                                               
   ██║   ██║   ██║                                               
   ██║   ╚██████╔╝                                               
   ╚═╝    ╚═════╝                                                
                                                                 
██╗    ██╗██╗██╗     ██████╗      ██████╗ █████╗ ██████╗ ██████╗ 
██║    ██║██║██║     ██╔══██╗    ██╔════╝██╔══██╗██╔══██╗██╔══██╗
██║ █╗ ██║██║██║     ██║  ██║    ██║     ███████║██████╔╝██║  ██║
██║███╗██║██║██║     ██║  ██║    ██║     ██╔══██║██╔══██╗██║  ██║
╚███╔███╔╝██║███████╗██████╔╝    ╚██████╗██║  ██║██║  ██║██████╔╝
 ╚══╝╚══╝ ╚═╝╚══════╝╚═════╝      ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝      
");
           
            menu();
        }

        // separate this class 
        // select option
        // displaying the menu 
        private void menu()
        {
            PrintBorder();
            Print(@"   Pick a game to play or see the credits");
            PrintBorder();

            List<string> options = new List<string>
            {
                "Same or Different",
                "Higher or Lower",
                "Highest Match",
                "Credits"
            };

            for(int i = 0; i < options.Count; i++)
            {
                Print($"  [{i + 1}] {options[i]} ");
            }

            PrintBorder();

            bool startGame = true;
            switch (GetInput())
            {
                case "1":
                    CurrentGame = new SameOrDifferent();
                    break;
                case "2":
                    CurrentGame = new HigherOrLower();
                    break;
                case "3":
                    CurrentGame = new HighestMatch();
                    break;
                case "4":
                    startGame = false;
                    displayCredits();
                    Pause();
                    break;
                default:
                    startGame = false;
                    Clear();
                    break;
            }

            if(startGame == true)
                BeginSelectedGame();
            else
                menu();   
        }
        private void BeginSelectedGame()
        {
            CurrentGame.BeginGame();
        }

        private void displayCredits(){
            Print("Made by: Saul");

            Print("Credits:");
            Print("ASCII art generated by: [https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20]");
        }
    }
}
