/*
 * Wildcard
 * saul enriquez, 3/17/25
 * 
 * credits: 
 * Turned text to ascii using [https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20]
 * Altered GetValues(Type) example from learn.microsoft.com [https://learn.microsoft.com/en-us/dotnet/api/system.enum.getvalues?view=net-9.0]
 * Used Equals(String) method example from learn.microsoft.com [https://learn.microsoft.com/en-us/dotnet/api/system.string.equals?view=net-9.0#system-string-equals(system-string-system-string)]
 * Game instructions for HigherOrLower, SameOrDifferent, HighestMatch were generated by [chatgpt.com]
 */

namespace Wildcard
{
    internal class Program
    {
        static void Main(string[] args)
        {
            new GameApplication().Start();
        }
    }
}
